### ISSUE TITLE
[Mod Compatibility] Backpacks!

### ISSUE THREAD

**Issue by OcAMD** [sidben/VisibleArmorSlots#12]
I just wanted to let you know there is a mod compatibility issue with [Backpacks!](https://minecraft.curseforge.com/projects/backpacks). I have tried it with 
Backpacks 3.1.7 for Minecraft 1.11.2 (tried first)
Backpacks 3.1.6 for Minecraft 1.11.2 (tried second)
forge-1.11.2-13.20.0.2227
VisibleArmorSlots[1.11.2]-3.0.jar

Backpacks returns to functionality after removing VisibleArmorSlots; I will report this to Backpacks as well.

**Comment by Brad16840** [comment]
I assume the issue you are referring to are the VisibleArmorSlots ceasing to function after you open another backpack or workbench within the same GUI.
 
If so the simplest way to fix this would be for VisibleArmorSlots to include a GUI blacklist on any brad16840.* GUI. 

A less simple way would be to have the GuiOverlay check if the GuiContainer still contains a VisibleArmorSlot 
(Backpacks! will automatically remove all VisibleArmorSlots from the client and the server when its GUIs change) and if not either stop rendering the background or treat it like a new GUI and add new VisibleArmorSlots.

If there is some other issue occurring you'll need to be more specific as that's the only issue I noticed

**Comment by OcAMD** [comment]
Yes the backpacks didn't function with VisibleArmorSlots installed. If you opened the backpacks and placed items into it upon closing they would return to the normal inventory. Also the creative size adjuster wouldn't function as well.

**Comment by Brad16840** [comment]
Oh... I didn't notice that it wasn't saving backpack modifications. 
A GUI blacklist should fix that issue.

**Comment by sidben** [comment]
I tested my new code with this backpack mod and it looks pretty stable. I'll finish up some details and release as beta this week.

The blacklist feature is already done, but for now it can make VisibleArmorSlots ignore the whole mod. In the future you'll be able to target individual GUI's.

**Comment by sidben** [comment]
Hello, I just published version 3.1.0 that should fix this issue. I tested the backback mod and a couple of others using forge 13.20.0.2233 and found no problems.

I'll keep this open for a few more days, but I'm considering the issue solved. Let me know if you have any problems.

**Comment by OcAMD** [comment]
I have just tried it and it seems to function properly now. I was able to adjust size of Backpacks and transfer items back and forth between various inventory screens. I was pleasantly surprised to see VisibleArmorSlots even functioning within the backpacks themselves. Thank you.

**Comment by sidben** [comment]
No problems, thanks for the report.
