### ISSUE TITLE
Slots overlap with Quark chest buttons

### ISSUE THREAD

**Issue by Thiana** [sidben/VisibleArmorSlots#2]
The slots overlap the buttons added to chests by Vazkii's Quark.

**Comment by sidben** [comment]
On the new 1.1 version I added some config options. You can position the slots on the right side of the inventory or keep them on the left and increase the margin to 20 or more, so they don't overlap.

Let me know if I can close this item.

**Comment by Thiana** [comment]
The settings are perfect :) Thank you.
